- name: Provision Python
  hosts: all
  gather_facts: false
  tasks:
    - name: Boostrap python
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3 openssh-client openssh-sftp-server && ln -sf /usr/lib/openssh/sftp-server /usr/lib/sftp-server && mkdir -p /root/.ansible/tmp)
 
- name: Install deps and copy source code
  hosts: default
  gather_facts: false
  roles:
    - role: ./roles/deps/
      vars:
        pip_packages: ["redis", "flask", "requests"]
  tasks:
    - name : "Copy source code to container"
      ansible.builtin.copy:
        src: "./azure-vote"
        dest: "/app"
        mode: "550"