---
- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: template custom index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Ensure Nginx service is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
